schema_version = "1.0.0"

id = "arch_sandv"
version = "1.0.0"
name = "Arch SandV"
tagline = "Edge and volume creation for arch features"
maintainer = "Benedict Dyson"
type = "add-on"
blender_version_min = "4.2.3"
license = ["SPDX:GPL-3.0-or-later"]
